{-
   Heron Data API

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.0
   Heron Data API API version: 2021-07-19
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

-- |
-- Module : HeronData.Lens
module HeronData.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Time as TI
import HeronData.Core
import HeronData.Model
import Prelude (Applicative, Bool (..), Char, Double, FilePath, Float, Functor, Int, Integer, Maybe (..), Monad, String, fmap, maybe, mempty, pure, undefined, ($), (.), (<$>), (<*>), (=<<))
import qualified Prelude as P

-- * Category

-- | 'categoryCreated' Lens
categoryCreatedL :: Lens_' Category (Maybe DateTime)
categoryCreatedL f Category {..} = (\categoryCreated -> Category {categoryCreated, ..}) <$> f categoryCreated
{-# INLINE categoryCreatedL #-}

-- | 'categoryDescription' Lens
categoryDescriptionL :: Lens_' Category (Maybe Text)
categoryDescriptionL f Category {..} = (\categoryDescription -> Category {categoryDescription, ..}) <$> f categoryDescription
{-# INLINE categoryDescriptionL #-}

-- | 'categoryHeronId' Lens
categoryHeronIdL :: Lens_' Category (Maybe Text)
categoryHeronIdL f Category {..} = (\categoryHeronId -> Category {categoryHeronId, ..}) <$> f categoryHeronId
{-# INLINE categoryHeronIdL #-}

-- | 'categoryLabel' Lens
categoryLabelL :: Lens_' Category (Text)
categoryLabelL f Category {..} = (\categoryLabel -> Category {categoryLabel, ..}) <$> f categoryLabel
{-# INLINE categoryLabelL #-}

-- * CategoryFeedback

-- | 'categoryFeedbackHeronId' Lens
categoryFeedbackHeronIdL :: Lens_' CategoryFeedback (Maybe Text)
categoryFeedbackHeronIdL f CategoryFeedback {..} = (\categoryFeedbackHeronId -> CategoryFeedback {categoryFeedbackHeronId, ..}) <$> f categoryFeedbackHeronId
{-# INLINE categoryFeedbackHeronIdL #-}

-- | 'categoryFeedbackLabel' Lens
categoryFeedbackLabelL :: Lens_' CategoryFeedback (Maybe Text)
categoryFeedbackLabelL f CategoryFeedback {..} = (\categoryFeedbackLabel -> CategoryFeedback {categoryFeedbackLabel, ..}) <$> f categoryFeedbackLabel
{-# INLINE categoryFeedbackLabelL #-}

-- * DeleteTransactionParams

-- | 'deleteTransactionParamsAccountId' Lens
deleteTransactionParamsAccountIdL :: Lens_' DeleteTransactionParams (Maybe Text)
deleteTransactionParamsAccountIdL f DeleteTransactionParams {..} = (\deleteTransactionParamsAccountId -> DeleteTransactionParams {deleteTransactionParamsAccountId, ..}) <$> f deleteTransactionParamsAccountId
{-# INLINE deleteTransactionParamsAccountIdL #-}

-- | 'deleteTransactionParamsEndUserId' Lens
deleteTransactionParamsEndUserIdL :: Lens_' DeleteTransactionParams (Maybe Text)
deleteTransactionParamsEndUserIdL f DeleteTransactionParams {..} = (\deleteTransactionParamsEndUserId -> DeleteTransactionParams {deleteTransactionParamsEndUserId, ..}) <$> f deleteTransactionParamsEndUserId
{-# INLINE deleteTransactionParamsEndUserIdL #-}

-- | 'deleteTransactionParamsHeronId' Lens
deleteTransactionParamsHeronIdL :: Lens_' DeleteTransactionParams (Maybe Text)
deleteTransactionParamsHeronIdL f DeleteTransactionParams {..} = (\deleteTransactionParamsHeronId -> DeleteTransactionParams {deleteTransactionParamsHeronId, ..}) <$> f deleteTransactionParamsHeronId
{-# INLINE deleteTransactionParamsHeronIdL #-}

-- | 'deleteTransactionParamsOnlyDuplicates' Lens
deleteTransactionParamsOnlyDuplicatesL :: Lens_' DeleteTransactionParams (Maybe Bool)
deleteTransactionParamsOnlyDuplicatesL f DeleteTransactionParams {..} = (\deleteTransactionParamsOnlyDuplicates -> DeleteTransactionParams {deleteTransactionParamsOnlyDuplicates, ..}) <$> f deleteTransactionParamsOnlyDuplicates
{-# INLINE deleteTransactionParamsOnlyDuplicatesL #-}

-- | 'deleteTransactionParamsRequestId' Lens
deleteTransactionParamsRequestIdL :: Lens_' DeleteTransactionParams (Maybe Text)
deleteTransactionParamsRequestIdL f DeleteTransactionParams {..} = (\deleteTransactionParamsRequestId -> DeleteTransactionParams {deleteTransactionParamsRequestId, ..}) <$> f deleteTransactionParamsRequestId
{-# INLINE deleteTransactionParamsRequestIdL #-}

-- * EndUser

-- | 'endUserConfidence' Lens
endUserConfidenceL :: Lens_' EndUser (Maybe Double)
endUserConfidenceL f EndUser {..} = (\endUserConfidence -> EndUser {endUserConfidence, ..}) <$> f endUserConfidence
{-# INLINE endUserConfidenceL #-}

-- | 'endUserCreated' Lens
endUserCreatedL :: Lens_' EndUser (Maybe DateTime)
endUserCreatedL f EndUser {..} = (\endUserCreated -> EndUser {endUserCreated, ..}) <$> f endUserCreated
{-# INLINE endUserCreatedL #-}

-- | 'endUserCriteria' Lens
endUserCriteriaL :: Lens_' EndUser (Maybe A.Value)
endUserCriteriaL f EndUser {..} = (\endUserCriteria -> EndUser {endUserCriteria, ..}) <$> f endUserCriteria
{-# INLINE endUserCriteriaL #-}

-- | 'endUserEndUserId' Lens
endUserEndUserIdL :: Lens_' EndUser (Text)
endUserEndUserIdL f EndUser {..} = (\endUserEndUserId -> EndUser {endUserEndUserId, ..}) <$> f endUserEndUserId
{-# INLINE endUserEndUserIdL #-}

-- | 'endUserHeronId' Lens
endUserHeronIdL :: Lens_' EndUser (Maybe Text)
endUserHeronIdL f EndUser {..} = (\endUserHeronId -> EndUser {endUserHeronId, ..}) <$> f endUserHeronId
{-# INLINE endUserHeronIdL #-}

-- | 'endUserLastUpdated' Lens
endUserLastUpdatedL :: Lens_' EndUser (Maybe DateTime)
endUserLastUpdatedL f EndUser {..} = (\endUserLastUpdated -> EndUser {endUserLastUpdated, ..}) <$> f endUserLastUpdated
{-# INLINE endUserLastUpdatedL #-}

-- | 'endUserName' Lens
endUserNameL :: Lens_' EndUser (Maybe Text)
endUserNameL f EndUser {..} = (\endUserName -> EndUser {endUserName, ..}) <$> f endUserName
{-# INLINE endUserNameL #-}

-- | 'endUserStatus' Lens
endUserStatusL :: Lens_' EndUser (E'Status)
endUserStatusL f EndUser {..} = (\endUserStatus -> EndUser {endUserStatus, ..}) <$> f endUserStatus
{-# INLINE endUserStatusL #-}

-- * EndUserBalanceInputParams

-- | 'endUserBalanceInputParamsEndUserHeronId' Lens
endUserBalanceInputParamsEndUserHeronIdL :: Lens_' EndUserBalanceInputParams (Maybe Text)
endUserBalanceInputParamsEndUserHeronIdL f EndUserBalanceInputParams {..} = (\endUserBalanceInputParamsEndUserHeronId -> EndUserBalanceInputParams {endUserBalanceInputParamsEndUserHeronId, ..}) <$> f endUserBalanceInputParamsEndUserHeronId
{-# INLINE endUserBalanceInputParamsEndUserHeronIdL #-}

-- | 'endUserBalanceInputParamsEndUserId' Lens
endUserBalanceInputParamsEndUserIdL :: Lens_' EndUserBalanceInputParams (Maybe Text)
endUserBalanceInputParamsEndUserIdL f EndUserBalanceInputParams {..} = (\endUserBalanceInputParamsEndUserId -> EndUserBalanceInputParams {endUserBalanceInputParamsEndUserId, ..}) <$> f endUserBalanceInputParamsEndUserId
{-# INLINE endUserBalanceInputParamsEndUserIdL #-}

-- | 'endUserBalanceInputParamsTimestampMax' Lens
endUserBalanceInputParamsTimestampMaxL :: Lens_' EndUserBalanceInputParams (Maybe DateTime)
endUserBalanceInputParamsTimestampMaxL f EndUserBalanceInputParams {..} = (\endUserBalanceInputParamsTimestampMax -> EndUserBalanceInputParams {endUserBalanceInputParamsTimestampMax, ..}) <$> f endUserBalanceInputParamsTimestampMax
{-# INLINE endUserBalanceInputParamsTimestampMaxL #-}

-- | 'endUserBalanceInputParamsTimestampMin' Lens
endUserBalanceInputParamsTimestampMinL :: Lens_' EndUserBalanceInputParams (Maybe DateTime)
endUserBalanceInputParamsTimestampMinL f EndUserBalanceInputParams {..} = (\endUserBalanceInputParamsTimestampMin -> EndUserBalanceInputParams {endUserBalanceInputParamsTimestampMin, ..}) <$> f endUserBalanceInputParamsTimestampMin
{-# INLINE endUserBalanceInputParamsTimestampMinL #-}

-- * EndUserForecastInputParams

-- | 'endUserForecastInputParamsCategoryHeronId' Lens
endUserForecastInputParamsCategoryHeronIdL :: Lens_' EndUserForecastInputParams (Maybe Text)
endUserForecastInputParamsCategoryHeronIdL f EndUserForecastInputParams {..} = (\endUserForecastInputParamsCategoryHeronId -> EndUserForecastInputParams {endUserForecastInputParamsCategoryHeronId, ..}) <$> f endUserForecastInputParamsCategoryHeronId
{-# INLINE endUserForecastInputParamsCategoryHeronIdL #-}

-- | 'endUserForecastInputParamsCategoryLabel' Lens
endUserForecastInputParamsCategoryLabelL :: Lens_' EndUserForecastInputParams (Maybe Text)
endUserForecastInputParamsCategoryLabelL f EndUserForecastInputParams {..} = (\endUserForecastInputParamsCategoryLabel -> EndUserForecastInputParams {endUserForecastInputParamsCategoryLabel, ..}) <$> f endUserForecastInputParamsCategoryLabel
{-# INLINE endUserForecastInputParamsCategoryLabelL #-}

-- | 'endUserForecastInputParamsDateGranularity' Lens
endUserForecastInputParamsDateGranularityL :: Lens_' EndUserForecastInputParams (Maybe E'DateGranularity)
endUserForecastInputParamsDateGranularityL f EndUserForecastInputParams {..} = (\endUserForecastInputParamsDateGranularity -> EndUserForecastInputParams {endUserForecastInputParamsDateGranularity, ..}) <$> f endUserForecastInputParamsDateGranularity
{-# INLINE endUserForecastInputParamsDateGranularityL #-}

-- | 'endUserForecastInputParamsEndUserHeronId' Lens
endUserForecastInputParamsEndUserHeronIdL :: Lens_' EndUserForecastInputParams (Maybe Text)
endUserForecastInputParamsEndUserHeronIdL f EndUserForecastInputParams {..} = (\endUserForecastInputParamsEndUserHeronId -> EndUserForecastInputParams {endUserForecastInputParamsEndUserHeronId, ..}) <$> f endUserForecastInputParamsEndUserHeronId
{-# INLINE endUserForecastInputParamsEndUserHeronIdL #-}

-- | 'endUserForecastInputParamsEndUserId' Lens
endUserForecastInputParamsEndUserIdL :: Lens_' EndUserForecastInputParams (Maybe Text)
endUserForecastInputParamsEndUserIdL f EndUserForecastInputParams {..} = (\endUserForecastInputParamsEndUserId -> EndUserForecastInputParams {endUserForecastInputParamsEndUserId, ..}) <$> f endUserForecastInputParamsEndUserId
{-# INLINE endUserForecastInputParamsEndUserIdL #-}

-- * EndUserForecastOutputSchema

-- | 'endUserForecastOutputSchemaDate' Lens
endUserForecastOutputSchemaDateL :: Lens_' EndUserForecastOutputSchema (Maybe Text)
endUserForecastOutputSchemaDateL f EndUserForecastOutputSchema {..} = (\endUserForecastOutputSchemaDate -> EndUserForecastOutputSchema {endUserForecastOutputSchemaDate, ..}) <$> f endUserForecastOutputSchemaDate
{-# INLINE endUserForecastOutputSchemaDateL #-}

-- | 'endUserForecastOutputSchemaPredicted' Lens
endUserForecastOutputSchemaPredictedL :: Lens_' EndUserForecastOutputSchema (Maybe Double)
endUserForecastOutputSchemaPredictedL f EndUserForecastOutputSchema {..} = (\endUserForecastOutputSchemaPredicted -> EndUserForecastOutputSchema {endUserForecastOutputSchemaPredicted, ..}) <$> f endUserForecastOutputSchemaPredicted
{-# INLINE endUserForecastOutputSchemaPredictedL #-}

-- | 'endUserForecastOutputSchemaPredictedLower' Lens
endUserForecastOutputSchemaPredictedLowerL :: Lens_' EndUserForecastOutputSchema (Maybe Double)
endUserForecastOutputSchemaPredictedLowerL f EndUserForecastOutputSchema {..} = (\endUserForecastOutputSchemaPredictedLower -> EndUserForecastOutputSchema {endUserForecastOutputSchemaPredictedLower, ..}) <$> f endUserForecastOutputSchemaPredictedLower
{-# INLINE endUserForecastOutputSchemaPredictedLowerL #-}

-- | 'endUserForecastOutputSchemaPredictedUpper' Lens
endUserForecastOutputSchemaPredictedUpperL :: Lens_' EndUserForecastOutputSchema (Maybe Double)
endUserForecastOutputSchemaPredictedUpperL f EndUserForecastOutputSchema {..} = (\endUserForecastOutputSchemaPredictedUpper -> EndUserForecastOutputSchema {endUserForecastOutputSchemaPredictedUpper, ..}) <$> f endUserForecastOutputSchemaPredictedUpper
{-# INLINE endUserForecastOutputSchemaPredictedUpperL #-}

-- * EndUserReadParams

-- | 'endUserReadParamsCriteria' Lens
endUserReadParamsCriteriaL :: Lens_' EndUserReadParams (Maybe A.Value)
endUserReadParamsCriteriaL f EndUserReadParams {..} = (\endUserReadParamsCriteria -> EndUserReadParams {endUserReadParamsCriteria, ..}) <$> f endUserReadParamsCriteria
{-# INLINE endUserReadParamsCriteriaL #-}

-- | 'endUserReadParamsEndUserId' Lens
endUserReadParamsEndUserIdL :: Lens_' EndUserReadParams (Maybe Text)
endUserReadParamsEndUserIdL f EndUserReadParams {..} = (\endUserReadParamsEndUserId -> EndUserReadParams {endUserReadParamsEndUserId, ..}) <$> f endUserReadParamsEndUserId
{-# INLINE endUserReadParamsEndUserIdL #-}

-- | 'endUserReadParamsHeronId' Lens
endUserReadParamsHeronIdL :: Lens_' EndUserReadParams (Maybe Text)
endUserReadParamsHeronIdL f EndUserReadParams {..} = (\endUserReadParamsHeronId -> EndUserReadParams {endUserReadParamsHeronId, ..}) <$> f endUserReadParamsHeronId
{-# INLINE endUserReadParamsHeronIdL #-}

-- | 'endUserReadParamsLimit' Lens
endUserReadParamsLimitL :: Lens_' EndUserReadParams (Maybe Int)
endUserReadParamsLimitL f EndUserReadParams {..} = (\endUserReadParamsLimit -> EndUserReadParams {endUserReadParamsLimit, ..}) <$> f endUserReadParamsLimit
{-# INLINE endUserReadParamsLimitL #-}

-- | 'endUserReadParamsName' Lens
endUserReadParamsNameL :: Lens_' EndUserReadParams (Maybe Text)
endUserReadParamsNameL f EndUserReadParams {..} = (\endUserReadParamsName -> EndUserReadParams {endUserReadParamsName, ..}) <$> f endUserReadParamsName
{-# INLINE endUserReadParamsNameL #-}

-- | 'endUserReadParamsOrderBy' Lens
endUserReadParamsOrderByL :: Lens_' EndUserReadParams (Maybe E'OrderBy)
endUserReadParamsOrderByL f EndUserReadParams {..} = (\endUserReadParamsOrderBy -> EndUserReadParams {endUserReadParamsOrderBy, ..}) <$> f endUserReadParamsOrderBy
{-# INLINE endUserReadParamsOrderByL #-}

-- | 'endUserReadParamsPage' Lens
endUserReadParamsPageL :: Lens_' EndUserReadParams (Maybe Int)
endUserReadParamsPageL f EndUserReadParams {..} = (\endUserReadParamsPage -> EndUserReadParams {endUserReadParamsPage, ..}) <$> f endUserReadParamsPage
{-# INLINE endUserReadParamsPageL #-}

-- | 'endUserReadParamsStatus' Lens
endUserReadParamsStatusL :: Lens_' EndUserReadParams (Maybe E'Status)
endUserReadParamsStatusL f EndUserReadParams {..} = (\endUserReadParamsStatus -> EndUserReadParams {endUserReadParamsStatus, ..}) <$> f endUserReadParamsStatus
{-# INLINE endUserReadParamsStatusL #-}

-- * EndUserStatsInputParams

-- | 'endUserStatsInputParamsCategoryHeronIds' Lens
endUserStatsInputParamsCategoryHeronIdsL :: Lens_' EndUserStatsInputParams (Maybe [Text])
endUserStatsInputParamsCategoryHeronIdsL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsCategoryHeronIds -> EndUserStatsInputParams {endUserStatsInputParamsCategoryHeronIds, ..}) <$> f endUserStatsInputParamsCategoryHeronIds
{-# INLINE endUserStatsInputParamsCategoryHeronIdsL #-}

-- | 'endUserStatsInputParamsDateGranularity' Lens
endUserStatsInputParamsDateGranularityL :: Lens_' EndUserStatsInputParams (Maybe E'DateGranularity2)
endUserStatsInputParamsDateGranularityL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsDateGranularity -> EndUserStatsInputParams {endUserStatsInputParamsDateGranularity, ..}) <$> f endUserStatsInputParamsDateGranularity
{-# INLINE endUserStatsInputParamsDateGranularityL #-}

-- | 'endUserStatsInputParamsEndUserHeronId' Lens
endUserStatsInputParamsEndUserHeronIdL :: Lens_' EndUserStatsInputParams (Maybe Text)
endUserStatsInputParamsEndUserHeronIdL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsEndUserHeronId -> EndUserStatsInputParams {endUserStatsInputParamsEndUserHeronId, ..}) <$> f endUserStatsInputParamsEndUserHeronId
{-# INLINE endUserStatsInputParamsEndUserHeronIdL #-}

-- | 'endUserStatsInputParamsEndUserId' Lens
endUserStatsInputParamsEndUserIdL :: Lens_' EndUserStatsInputParams (Maybe Text)
endUserStatsInputParamsEndUserIdL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsEndUserId -> EndUserStatsInputParams {endUserStatsInputParamsEndUserId, ..}) <$> f endUserStatsInputParamsEndUserId
{-# INLINE endUserStatsInputParamsEndUserIdL #-}

-- | 'endUserStatsInputParamsFromDate' Lens
endUserStatsInputParamsFromDateL :: Lens_' EndUserStatsInputParams (Maybe Date)
endUserStatsInputParamsFromDateL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsFromDate -> EndUserStatsInputParams {endUserStatsInputParamsFromDate, ..}) <$> f endUserStatsInputParamsFromDate
{-# INLINE endUserStatsInputParamsFromDateL #-}

-- | 'endUserStatsInputParamsGroupBy' Lens
endUserStatsInputParamsGroupByL :: Lens_' EndUserStatsInputParams (Maybe E'GroupBy)
endUserStatsInputParamsGroupByL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsGroupBy -> EndUserStatsInputParams {endUserStatsInputParamsGroupBy, ..}) <$> f endUserStatsInputParamsGroupBy
{-# INLINE endUserStatsInputParamsGroupByL #-}

-- | 'endUserStatsInputParamsMerchantHeronIds' Lens
endUserStatsInputParamsMerchantHeronIdsL :: Lens_' EndUserStatsInputParams (Maybe [Text])
endUserStatsInputParamsMerchantHeronIdsL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsMerchantHeronIds -> EndUserStatsInputParams {endUserStatsInputParamsMerchantHeronIds, ..}) <$> f endUserStatsInputParamsMerchantHeronIds
{-# INLINE endUserStatsInputParamsMerchantHeronIdsL #-}

-- | 'endUserStatsInputParamsToDate' Lens
endUserStatsInputParamsToDateL :: Lens_' EndUserStatsInputParams (Maybe Date)
endUserStatsInputParamsToDateL f EndUserStatsInputParams {..} = (\endUserStatsInputParamsToDate -> EndUserStatsInputParams {endUserStatsInputParamsToDate, ..}) <$> f endUserStatsInputParamsToDate
{-# INLINE endUserStatsInputParamsToDateL #-}

-- * GetTransactionParams

-- | 'getTransactionParamsCategoryHeronId' Lens
getTransactionParamsCategoryHeronIdL :: Lens_' GetTransactionParams (Maybe [Text])
getTransactionParamsCategoryHeronIdL f GetTransactionParams {..} = (\getTransactionParamsCategoryHeronId -> GetTransactionParams {getTransactionParamsCategoryHeronId, ..}) <$> f getTransactionParamsCategoryHeronId
{-# INLINE getTransactionParamsCategoryHeronIdL #-}

-- | 'getTransactionParamsConfidenceMax' Lens
getTransactionParamsConfidenceMaxL :: Lens_' GetTransactionParams (Maybe Double)
getTransactionParamsConfidenceMaxL f GetTransactionParams {..} = (\getTransactionParamsConfidenceMax -> GetTransactionParams {getTransactionParamsConfidenceMax, ..}) <$> f getTransactionParamsConfidenceMax
{-# INLINE getTransactionParamsConfidenceMaxL #-}

-- | 'getTransactionParamsConfidenceMin' Lens
getTransactionParamsConfidenceMinL :: Lens_' GetTransactionParams (Maybe Double)
getTransactionParamsConfidenceMinL f GetTransactionParams {..} = (\getTransactionParamsConfidenceMin -> GetTransactionParams {getTransactionParamsConfidenceMin, ..}) <$> f getTransactionParamsConfidenceMin
{-# INLINE getTransactionParamsConfidenceMinL #-}

-- | 'getTransactionParamsCreatedDateMax' Lens
getTransactionParamsCreatedDateMaxL :: Lens_' GetTransactionParams (Maybe Date)
getTransactionParamsCreatedDateMaxL f GetTransactionParams {..} = (\getTransactionParamsCreatedDateMax -> GetTransactionParams {getTransactionParamsCreatedDateMax, ..}) <$> f getTransactionParamsCreatedDateMax
{-# INLINE getTransactionParamsCreatedDateMaxL #-}

-- | 'getTransactionParamsCreatedDateMin' Lens
getTransactionParamsCreatedDateMinL :: Lens_' GetTransactionParams (Maybe Date)
getTransactionParamsCreatedDateMinL f GetTransactionParams {..} = (\getTransactionParamsCreatedDateMin -> GetTransactionParams {getTransactionParamsCreatedDateMin, ..}) <$> f getTransactionParamsCreatedDateMin
{-# INLINE getTransactionParamsCreatedDateMinL #-}

-- | 'getTransactionParamsDescriptionKeyword' Lens
getTransactionParamsDescriptionKeywordL :: Lens_' GetTransactionParams (Maybe Text)
getTransactionParamsDescriptionKeywordL f GetTransactionParams {..} = (\getTransactionParamsDescriptionKeyword -> GetTransactionParams {getTransactionParamsDescriptionKeyword, ..}) <$> f getTransactionParamsDescriptionKeyword
{-# INLINE getTransactionParamsDescriptionKeywordL #-}

-- | 'getTransactionParamsDescriptionRegex' Lens
getTransactionParamsDescriptionRegexL :: Lens_' GetTransactionParams (Maybe Text)
getTransactionParamsDescriptionRegexL f GetTransactionParams {..} = (\getTransactionParamsDescriptionRegex -> GetTransactionParams {getTransactionParamsDescriptionRegex, ..}) <$> f getTransactionParamsDescriptionRegex
{-# INLINE getTransactionParamsDescriptionRegexL #-}

-- | 'getTransactionParamsEndUserId' Lens
getTransactionParamsEndUserIdL :: Lens_' GetTransactionParams (Maybe Text)
getTransactionParamsEndUserIdL f GetTransactionParams {..} = (\getTransactionParamsEndUserId -> GetTransactionParams {getTransactionParamsEndUserId, ..}) <$> f getTransactionParamsEndUserId
{-# INLINE getTransactionParamsEndUserIdL #-}

-- | 'getTransactionParamsFromDate' Lens
getTransactionParamsFromDateL :: Lens_' GetTransactionParams (Maybe Date)
getTransactionParamsFromDateL f GetTransactionParams {..} = (\getTransactionParamsFromDate -> GetTransactionParams {getTransactionParamsFromDate, ..}) <$> f getTransactionParamsFromDate
{-# INLINE getTransactionParamsFromDateL #-}

-- | 'getTransactionParamsHasMatchingTransaction' Lens
getTransactionParamsHasMatchingTransactionL :: Lens_' GetTransactionParams (Maybe Bool)
getTransactionParamsHasMatchingTransactionL f GetTransactionParams {..} = (\getTransactionParamsHasMatchingTransaction -> GetTransactionParams {getTransactionParamsHasMatchingTransaction, ..}) <$> f getTransactionParamsHasMatchingTransaction
{-# INLINE getTransactionParamsHasMatchingTransactionL #-}

-- | 'getTransactionParamsHeronId' Lens
getTransactionParamsHeronIdL :: Lens_' GetTransactionParams (Maybe Text)
getTransactionParamsHeronIdL f GetTransactionParams {..} = (\getTransactionParamsHeronId -> GetTransactionParams {getTransactionParamsHeronId, ..}) <$> f getTransactionParamsHeronId
{-# INLINE getTransactionParamsHeronIdL #-}

-- | 'getTransactionParamsIncludeDuplicates' Lens
getTransactionParamsIncludeDuplicatesL :: Lens_' GetTransactionParams (Maybe Bool)
getTransactionParamsIncludeDuplicatesL f GetTransactionParams {..} = (\getTransactionParamsIncludeDuplicates -> GetTransactionParams {getTransactionParamsIncludeDuplicates, ..}) <$> f getTransactionParamsIncludeDuplicates
{-# INLINE getTransactionParamsIncludeDuplicatesL #-}

-- | 'getTransactionParamsIsRecurring' Lens
getTransactionParamsIsRecurringL :: Lens_' GetTransactionParams (Maybe Bool)
getTransactionParamsIsRecurringL f GetTransactionParams {..} = (\getTransactionParamsIsRecurring -> GetTransactionParams {getTransactionParamsIsRecurring, ..}) <$> f getTransactionParamsIsRecurring
{-# INLINE getTransactionParamsIsRecurringL #-}

-- | 'getTransactionParamsLastUpdatedMax' Lens
getTransactionParamsLastUpdatedMaxL :: Lens_' GetTransactionParams (Maybe DateTime)
getTransactionParamsLastUpdatedMaxL f GetTransactionParams {..} = (\getTransactionParamsLastUpdatedMax -> GetTransactionParams {getTransactionParamsLastUpdatedMax, ..}) <$> f getTransactionParamsLastUpdatedMax
{-# INLINE getTransactionParamsLastUpdatedMaxL #-}

-- | 'getTransactionParamsLastUpdatedMin' Lens
getTransactionParamsLastUpdatedMinL :: Lens_' GetTransactionParams (Maybe DateTime)
getTransactionParamsLastUpdatedMinL f GetTransactionParams {..} = (\getTransactionParamsLastUpdatedMin -> GetTransactionParams {getTransactionParamsLastUpdatedMin, ..}) <$> f getTransactionParamsLastUpdatedMin
{-# INLINE getTransactionParamsLastUpdatedMinL #-}

-- | 'getTransactionParamsLimit' Lens
getTransactionParamsLimitL :: Lens_' GetTransactionParams (Maybe Int)
getTransactionParamsLimitL f GetTransactionParams {..} = (\getTransactionParamsLimit -> GetTransactionParams {getTransactionParamsLimit, ..}) <$> f getTransactionParamsLimit
{-# INLINE getTransactionParamsLimitL #-}

-- | 'getTransactionParamsMaxAmount' Lens
getTransactionParamsMaxAmountL :: Lens_' GetTransactionParams (Maybe Double)
getTransactionParamsMaxAmountL f GetTransactionParams {..} = (\getTransactionParamsMaxAmount -> GetTransactionParams {getTransactionParamsMaxAmount, ..}) <$> f getTransactionParamsMaxAmount
{-# INLINE getTransactionParamsMaxAmountL #-}

-- | 'getTransactionParamsMinAmount' Lens
getTransactionParamsMinAmountL :: Lens_' GetTransactionParams (Maybe Double)
getTransactionParamsMinAmountL f GetTransactionParams {..} = (\getTransactionParamsMinAmount -> GetTransactionParams {getTransactionParamsMinAmount, ..}) <$> f getTransactionParamsMinAmount
{-# INLINE getTransactionParamsMinAmountL #-}

-- | 'getTransactionParamsOrderBy' Lens
getTransactionParamsOrderByL :: Lens_' GetTransactionParams (Maybe E'OrderBy2)
getTransactionParamsOrderByL f GetTransactionParams {..} = (\getTransactionParamsOrderBy -> GetTransactionParams {getTransactionParamsOrderBy, ..}) <$> f getTransactionParamsOrderBy
{-# INLINE getTransactionParamsOrderByL #-}

-- | 'getTransactionParamsPage' Lens
getTransactionParamsPageL :: Lens_' GetTransactionParams (Maybe Int)
getTransactionParamsPageL f GetTransactionParams {..} = (\getTransactionParamsPage -> GetTransactionParams {getTransactionParamsPage, ..}) <$> f getTransactionParamsPage
{-# INLINE getTransactionParamsPageL #-}

-- | 'getTransactionParamsReferenceId' Lens
getTransactionParamsReferenceIdL :: Lens_' GetTransactionParams (Maybe Text)
getTransactionParamsReferenceIdL f GetTransactionParams {..} = (\getTransactionParamsReferenceId -> GetTransactionParams {getTransactionParamsReferenceId, ..}) <$> f getTransactionParamsReferenceId
{-# INLINE getTransactionParamsReferenceIdL #-}

-- | 'getTransactionParamsRequestId' Lens
getTransactionParamsRequestIdL :: Lens_' GetTransactionParams (Maybe Text)
getTransactionParamsRequestIdL f GetTransactionParams {..} = (\getTransactionParamsRequestId -> GetTransactionParams {getTransactionParamsRequestId, ..}) <$> f getTransactionParamsRequestId
{-# INLINE getTransactionParamsRequestIdL #-}

-- | 'getTransactionParamsTimestampDateMax' Lens
getTransactionParamsTimestampDateMaxL :: Lens_' GetTransactionParams (Maybe Date)
getTransactionParamsTimestampDateMaxL f GetTransactionParams {..} = (\getTransactionParamsTimestampDateMax -> GetTransactionParams {getTransactionParamsTimestampDateMax, ..}) <$> f getTransactionParamsTimestampDateMax
{-# INLINE getTransactionParamsTimestampDateMaxL #-}

-- | 'getTransactionParamsTimestampDateMin' Lens
getTransactionParamsTimestampDateMinL :: Lens_' GetTransactionParams (Maybe Date)
getTransactionParamsTimestampDateMinL f GetTransactionParams {..} = (\getTransactionParamsTimestampDateMin -> GetTransactionParams {getTransactionParamsTimestampDateMin, ..}) <$> f getTransactionParamsTimestampDateMin
{-# INLINE getTransactionParamsTimestampDateMinL #-}

-- | 'getTransactionParamsToDate' Lens
getTransactionParamsToDateL :: Lens_' GetTransactionParams (Maybe Date)
getTransactionParamsToDateL f GetTransactionParams {..} = (\getTransactionParamsToDate -> GetTransactionParams {getTransactionParamsToDate, ..}) <$> f getTransactionParamsToDate
{-# INLINE getTransactionParamsToDateL #-}

-- | 'getTransactionParamsTransactionCode' Lens
getTransactionParamsTransactionCodeL :: Lens_' GetTransactionParams (Maybe Text)
getTransactionParamsTransactionCodeL f GetTransactionParams {..} = (\getTransactionParamsTransactionCode -> GetTransactionParams {getTransactionParamsTransactionCode, ..}) <$> f getTransactionParamsTransactionCode
{-# INLINE getTransactionParamsTransactionCodeL #-}

-- * InlineObject

-- | 'inlineObjectEndUser' Lens
inlineObjectEndUserL :: Lens_' InlineObject (Maybe EndUser)
inlineObjectEndUserL f InlineObject {..} = (\inlineObjectEndUser -> InlineObject {inlineObjectEndUser, ..}) <$> f inlineObjectEndUser
{-# INLINE inlineObjectEndUserL #-}

-- * InlineObject1

-- | 'inlineObject1EndUser' Lens
inlineObject1EndUserL :: Lens_' InlineObject1 (Maybe EndUser)
inlineObject1EndUserL f InlineObject1 {..} = (\inlineObject1EndUser -> InlineObject1 {inlineObject1EndUser, ..}) <$> f inlineObject1EndUser
{-# INLINE inlineObject1EndUserL #-}

-- * InlineObject2

-- | 'inlineObject2Description' Lens
inlineObject2DescriptionL :: Lens_' InlineObject2 (Maybe Text)
inlineObject2DescriptionL f InlineObject2 {..} = (\inlineObject2Description -> InlineObject2 {inlineObject2Description, ..}) <$> f inlineObject2Description
{-# INLINE inlineObject2DescriptionL #-}

-- * InlineObject3

-- | 'inlineObject3Transactions' Lens
inlineObject3TransactionsL :: Lens_' InlineObject3 (Maybe [TransactionInput])
inlineObject3TransactionsL f InlineObject3 {..} = (\inlineObject3Transactions -> InlineObject3 {inlineObject3Transactions, ..}) <$> f inlineObject3Transactions
{-# INLINE inlineObject3TransactionsL #-}

-- * InlineObject4

-- | 'inlineObject4Transaction' Lens
inlineObject4TransactionL :: Lens_' InlineObject4 (Maybe TransactionFeedbackSchema)
inlineObject4TransactionL f InlineObject4 {..} = (\inlineObject4Transaction -> InlineObject4 {inlineObject4Transaction, ..}) <$> f inlineObject4Transaction
{-# INLINE inlineObject4TransactionL #-}

-- * InlineResponse200

-- | 'inlineResponse200Categories' Lens
inlineResponse200CategoriesL :: Lens_' InlineResponse200 (Maybe [Category])
inlineResponse200CategoriesL f InlineResponse200 {..} = (\inlineResponse200Categories -> InlineResponse200 {inlineResponse200Categories, ..}) <$> f inlineResponse200Categories
{-# INLINE inlineResponse200CategoriesL #-}

-- * InlineResponse2001

-- | 'inlineResponse2001Meta' Lens
inlineResponse2001MetaL :: Lens_' InlineResponse2001 (Maybe InlineResponse2001Meta)
inlineResponse2001MetaL f InlineResponse2001 {..} = (\inlineResponse2001Meta -> InlineResponse2001 {inlineResponse2001Meta, ..}) <$> f inlineResponse2001Meta
{-# INLINE inlineResponse2001MetaL #-}

-- | 'inlineResponse2001EndUsers' Lens
inlineResponse2001EndUsersL :: Lens_' InlineResponse2001 (Maybe [EndUser])
inlineResponse2001EndUsersL f InlineResponse2001 {..} = (\inlineResponse2001EndUsers -> InlineResponse2001 {inlineResponse2001EndUsers, ..}) <$> f inlineResponse2001EndUsers
{-# INLINE inlineResponse2001EndUsersL #-}

-- * InlineResponse2001Meta

-- | 'inlineResponse2001MetaLimit' Lens
inlineResponse2001MetaLimitL :: Lens_' InlineResponse2001Meta (Maybe Int)
inlineResponse2001MetaLimitL f InlineResponse2001Meta {..} = (\inlineResponse2001MetaLimit -> InlineResponse2001Meta {inlineResponse2001MetaLimit, ..}) <$> f inlineResponse2001MetaLimit
{-# INLINE inlineResponse2001MetaLimitL #-}

-- | 'inlineResponse2001MetaNextUrl' Lens
inlineResponse2001MetaNextUrlL :: Lens_' InlineResponse2001Meta (Maybe Text)
inlineResponse2001MetaNextUrlL f InlineResponse2001Meta {..} = (\inlineResponse2001MetaNextUrl -> InlineResponse2001Meta {inlineResponse2001MetaNextUrl, ..}) <$> f inlineResponse2001MetaNextUrl
{-# INLINE inlineResponse2001MetaNextUrlL #-}

-- | 'inlineResponse2001MetaPage' Lens
inlineResponse2001MetaPageL :: Lens_' InlineResponse2001Meta (Maybe Int)
inlineResponse2001MetaPageL f InlineResponse2001Meta {..} = (\inlineResponse2001MetaPage -> InlineResponse2001Meta {inlineResponse2001MetaPage, ..}) <$> f inlineResponse2001MetaPage
{-# INLINE inlineResponse2001MetaPageL #-}

-- | 'inlineResponse2001MetaPages' Lens
inlineResponse2001MetaPagesL :: Lens_' InlineResponse2001Meta (Maybe Int)
inlineResponse2001MetaPagesL f InlineResponse2001Meta {..} = (\inlineResponse2001MetaPages -> InlineResponse2001Meta {inlineResponse2001MetaPages, ..}) <$> f inlineResponse2001MetaPages
{-# INLINE inlineResponse2001MetaPagesL #-}

-- | 'inlineResponse2001MetaPrevUrl' Lens
inlineResponse2001MetaPrevUrlL :: Lens_' InlineResponse2001Meta (Maybe Text)
inlineResponse2001MetaPrevUrlL f InlineResponse2001Meta {..} = (\inlineResponse2001MetaPrevUrl -> InlineResponse2001Meta {inlineResponse2001MetaPrevUrl, ..}) <$> f inlineResponse2001MetaPrevUrl
{-# INLINE inlineResponse2001MetaPrevUrlL #-}

-- | 'inlineResponse2001MetaTotal' Lens
inlineResponse2001MetaTotalL :: Lens_' InlineResponse2001Meta (Maybe Int)
inlineResponse2001MetaTotalL f InlineResponse2001Meta {..} = (\inlineResponse2001MetaTotal -> InlineResponse2001Meta {inlineResponse2001MetaTotal, ..}) <$> f inlineResponse2001MetaTotal
{-# INLINE inlineResponse2001MetaTotalL #-}

-- * InlineResponse2002

-- | 'inlineResponse2002Accounts' Lens
inlineResponse2002AccountsL :: Lens_' InlineResponse2002 (Maybe [InlineResponse2002Accounts])
inlineResponse2002AccountsL f InlineResponse2002 {..} = (\inlineResponse2002Accounts -> InlineResponse2002 {inlineResponse2002Accounts, ..}) <$> f inlineResponse2002Accounts
{-# INLINE inlineResponse2002AccountsL #-}

-- | 'inlineResponse2002Summary' Lens
inlineResponse2002SummaryL :: Lens_' InlineResponse2002 (Maybe InlineResponse2002Summary)
inlineResponse2002SummaryL f InlineResponse2002 {..} = (\inlineResponse2002Summary -> InlineResponse2002 {inlineResponse2002Summary, ..}) <$> f inlineResponse2002Summary
{-# INLINE inlineResponse2002SummaryL #-}

-- * InlineResponse2002Accounts

-- | 'inlineResponse2002AccountsAccountId' Lens
inlineResponse2002AccountsAccountIdL :: Lens_' InlineResponse2002Accounts (Maybe Text)
inlineResponse2002AccountsAccountIdL f InlineResponse2002Accounts {..} = (\inlineResponse2002AccountsAccountId -> InlineResponse2002Accounts {inlineResponse2002AccountsAccountId, ..}) <$> f inlineResponse2002AccountsAccountId
{-# INLINE inlineResponse2002AccountsAccountIdL #-}

-- | 'inlineResponse2002AccountsBalance' Lens
inlineResponse2002AccountsBalanceL :: Lens_' InlineResponse2002Accounts (Maybe Double)
inlineResponse2002AccountsBalanceL f InlineResponse2002Accounts {..} = (\inlineResponse2002AccountsBalance -> InlineResponse2002Accounts {inlineResponse2002AccountsBalance, ..}) <$> f inlineResponse2002AccountsBalance
{-# INLINE inlineResponse2002AccountsBalanceL #-}

-- | 'inlineResponse2002AccountsLastTransactionTimestamp' Lens
inlineResponse2002AccountsLastTransactionTimestampL :: Lens_' InlineResponse2002Accounts (Maybe DateTime)
inlineResponse2002AccountsLastTransactionTimestampL f InlineResponse2002Accounts {..} = (\inlineResponse2002AccountsLastTransactionTimestamp -> InlineResponse2002Accounts {inlineResponse2002AccountsLastTransactionTimestamp, ..}) <$> f inlineResponse2002AccountsLastTransactionTimestamp
{-# INLINE inlineResponse2002AccountsLastTransactionTimestampL #-}

-- * InlineResponse2002Summary

-- | 'inlineResponse2002SummaryBalance' Lens
inlineResponse2002SummaryBalanceL :: Lens_' InlineResponse2002Summary (Maybe Double)
inlineResponse2002SummaryBalanceL f InlineResponse2002Summary {..} = (\inlineResponse2002SummaryBalance -> InlineResponse2002Summary {inlineResponse2002SummaryBalance, ..}) <$> f inlineResponse2002SummaryBalance
{-# INLINE inlineResponse2002SummaryBalanceL #-}

-- | 'inlineResponse2002SummaryTimestamp' Lens
inlineResponse2002SummaryTimestampL :: Lens_' InlineResponse2002Summary (Maybe DateTime)
inlineResponse2002SummaryTimestampL f InlineResponse2002Summary {..} = (\inlineResponse2002SummaryTimestamp -> InlineResponse2002Summary {inlineResponse2002SummaryTimestamp, ..}) <$> f inlineResponse2002SummaryTimestamp
{-# INLINE inlineResponse2002SummaryTimestampL #-}

-- * InlineResponse2003

-- | 'inlineResponse2003Statistics' Lens
inlineResponse2003StatisticsL :: Lens_' InlineResponse2003 (Maybe [InlineResponse2003Statistics])
inlineResponse2003StatisticsL f InlineResponse2003 {..} = (\inlineResponse2003Statistics -> InlineResponse2003 {inlineResponse2003Statistics, ..}) <$> f inlineResponse2003Statistics
{-# INLINE inlineResponse2003StatisticsL #-}

-- * InlineResponse2003Statistics

-- | 'inlineResponse2003StatisticsDt' Lens
inlineResponse2003StatisticsDtL :: Lens_' InlineResponse2003Statistics (Maybe Text)
inlineResponse2003StatisticsDtL f InlineResponse2003Statistics {..} = (\inlineResponse2003StatisticsDt -> InlineResponse2003Statistics {inlineResponse2003StatisticsDt, ..}) <$> f inlineResponse2003StatisticsDt
{-# INLINE inlineResponse2003StatisticsDtL #-}

-- | 'inlineResponse2003StatisticsHeronId' Lens
inlineResponse2003StatisticsHeronIdL :: Lens_' InlineResponse2003Statistics (Maybe Text)
inlineResponse2003StatisticsHeronIdL f InlineResponse2003Statistics {..} = (\inlineResponse2003StatisticsHeronId -> InlineResponse2003Statistics {inlineResponse2003StatisticsHeronId, ..}) <$> f inlineResponse2003StatisticsHeronId
{-# INLINE inlineResponse2003StatisticsHeronIdL #-}

-- | 'inlineResponse2003StatisticsLabel' Lens
inlineResponse2003StatisticsLabelL :: Lens_' InlineResponse2003Statistics (Maybe Text)
inlineResponse2003StatisticsLabelL f InlineResponse2003Statistics {..} = (\inlineResponse2003StatisticsLabel -> InlineResponse2003Statistics {inlineResponse2003StatisticsLabel, ..}) <$> f inlineResponse2003StatisticsLabel
{-# INLINE inlineResponse2003StatisticsLabelL #-}

-- | 'inlineResponse2003StatisticsValue' Lens
inlineResponse2003StatisticsValueL :: Lens_' InlineResponse2003Statistics (Maybe Double)
inlineResponse2003StatisticsValueL f InlineResponse2003Statistics {..} = (\inlineResponse2003StatisticsValue -> InlineResponse2003Statistics {inlineResponse2003StatisticsValue, ..}) <$> f inlineResponse2003StatisticsValue
{-# INLINE inlineResponse2003StatisticsValueL #-}

-- * InlineResponse2004

-- | 'inlineResponse2004Hello' Lens
inlineResponse2004HelloL :: Lens_' InlineResponse2004 (Maybe Text)
inlineResponse2004HelloL f InlineResponse2004 {..} = (\inlineResponse2004Hello -> InlineResponse2004 {inlineResponse2004Hello, ..}) <$> f inlineResponse2004Hello
{-# INLINE inlineResponse2004HelloL #-}

-- * InlineResponse2005

-- | 'inlineResponse2005DescriptionClean' Lens
inlineResponse2005DescriptionCleanL :: Lens_' InlineResponse2005 (Maybe Text)
inlineResponse2005DescriptionCleanL f InlineResponse2005 {..} = (\inlineResponse2005DescriptionClean -> InlineResponse2005 {inlineResponse2005DescriptionClean, ..}) <$> f inlineResponse2005DescriptionClean
{-# INLINE inlineResponse2005DescriptionCleanL #-}

-- | 'inlineResponse2005Merchant' Lens
inlineResponse2005MerchantL :: Lens_' InlineResponse2005 (Maybe MerchantExtract)
inlineResponse2005MerchantL f InlineResponse2005 {..} = (\inlineResponse2005Merchant -> InlineResponse2005 {inlineResponse2005Merchant, ..}) <$> f inlineResponse2005Merchant
{-# INLINE inlineResponse2005MerchantL #-}

-- | 'inlineResponse2005PaymentProcessor' Lens
inlineResponse2005PaymentProcessorL :: Lens_' InlineResponse2005 (Maybe PaymentProcessor)
inlineResponse2005PaymentProcessorL f InlineResponse2005 {..} = (\inlineResponse2005PaymentProcessor -> InlineResponse2005 {inlineResponse2005PaymentProcessor, ..}) <$> f inlineResponse2005PaymentProcessor
{-# INLINE inlineResponse2005PaymentProcessorL #-}

-- * InlineResponse2006

-- | 'inlineResponse2006Merchants' Lens
inlineResponse2006MerchantsL :: Lens_' InlineResponse2006 (Maybe [Merchant])
inlineResponse2006MerchantsL f InlineResponse2006 {..} = (\inlineResponse2006Merchants -> InlineResponse2006 {inlineResponse2006Merchants, ..}) <$> f inlineResponse2006Merchants
{-# INLINE inlineResponse2006MerchantsL #-}

-- * InlineResponse2007

-- | 'inlineResponse2007Merchant' Lens
inlineResponse2007MerchantL :: Lens_' InlineResponse2007 (Maybe Merchant)
inlineResponse2007MerchantL f InlineResponse2007 {..} = (\inlineResponse2007Merchant -> InlineResponse2007 {inlineResponse2007Merchant, ..}) <$> f inlineResponse2007Merchant
{-# INLINE inlineResponse2007MerchantL #-}

-- * InlineResponse2008

-- | 'inlineResponse2008Meta' Lens
inlineResponse2008MetaL :: Lens_' InlineResponse2008 (Maybe InlineResponse2008Meta)
inlineResponse2008MetaL f InlineResponse2008 {..} = (\inlineResponse2008Meta -> InlineResponse2008 {inlineResponse2008Meta, ..}) <$> f inlineResponse2008Meta
{-# INLINE inlineResponse2008MetaL #-}

-- | 'inlineResponse2008Summary' Lens
inlineResponse2008SummaryL :: Lens_' InlineResponse2008 (Maybe InlineResponse2008Summary)
inlineResponse2008SummaryL f InlineResponse2008 {..} = (\inlineResponse2008Summary -> InlineResponse2008 {inlineResponse2008Summary, ..}) <$> f inlineResponse2008Summary
{-# INLINE inlineResponse2008SummaryL #-}

-- | 'inlineResponse2008Transactions' Lens
inlineResponse2008TransactionsL :: Lens_' InlineResponse2008 (Maybe [TransactionGetOutput])
inlineResponse2008TransactionsL f InlineResponse2008 {..} = (\inlineResponse2008Transactions -> InlineResponse2008 {inlineResponse2008Transactions, ..}) <$> f inlineResponse2008Transactions
{-# INLINE inlineResponse2008TransactionsL #-}

-- * InlineResponse2008Meta

-- | 'inlineResponse2008MetaNextUrl' Lens
inlineResponse2008MetaNextUrlL :: Lens_' InlineResponse2008Meta (Maybe Text)
inlineResponse2008MetaNextUrlL f InlineResponse2008Meta {..} = (\inlineResponse2008MetaNextUrl -> InlineResponse2008Meta {inlineResponse2008MetaNextUrl, ..}) <$> f inlineResponse2008MetaNextUrl
{-# INLINE inlineResponse2008MetaNextUrlL #-}

-- | 'inlineResponse2008MetaPage' Lens
inlineResponse2008MetaPageL :: Lens_' InlineResponse2008Meta (Maybe Int)
inlineResponse2008MetaPageL f InlineResponse2008Meta {..} = (\inlineResponse2008MetaPage -> InlineResponse2008Meta {inlineResponse2008MetaPage, ..}) <$> f inlineResponse2008MetaPage
{-# INLINE inlineResponse2008MetaPageL #-}

-- | 'inlineResponse2008MetaPages' Lens
inlineResponse2008MetaPagesL :: Lens_' InlineResponse2008Meta (Maybe Int)
inlineResponse2008MetaPagesL f InlineResponse2008Meta {..} = (\inlineResponse2008MetaPages -> InlineResponse2008Meta {inlineResponse2008MetaPages, ..}) <$> f inlineResponse2008MetaPages
{-# INLINE inlineResponse2008MetaPagesL #-}

-- | 'inlineResponse2008MetaPerPage' Lens
inlineResponse2008MetaPerPageL :: Lens_' InlineResponse2008Meta (Maybe Int)
inlineResponse2008MetaPerPageL f InlineResponse2008Meta {..} = (\inlineResponse2008MetaPerPage -> InlineResponse2008Meta {inlineResponse2008MetaPerPage, ..}) <$> f inlineResponse2008MetaPerPage
{-# INLINE inlineResponse2008MetaPerPageL #-}

-- | 'inlineResponse2008MetaPrevUrl' Lens
inlineResponse2008MetaPrevUrlL :: Lens_' InlineResponse2008Meta (Maybe Text)
inlineResponse2008MetaPrevUrlL f InlineResponse2008Meta {..} = (\inlineResponse2008MetaPrevUrl -> InlineResponse2008Meta {inlineResponse2008MetaPrevUrl, ..}) <$> f inlineResponse2008MetaPrevUrl
{-# INLINE inlineResponse2008MetaPrevUrlL #-}

-- * InlineResponse2008Summary

-- | 'inlineResponse2008SummaryReturnedTransactions' Lens
inlineResponse2008SummaryReturnedTransactionsL :: Lens_' InlineResponse2008Summary (Maybe Int)
inlineResponse2008SummaryReturnedTransactionsL f InlineResponse2008Summary {..} = (\inlineResponse2008SummaryReturnedTransactions -> InlineResponse2008Summary {inlineResponse2008SummaryReturnedTransactions, ..}) <$> f inlineResponse2008SummaryReturnedTransactions
{-# INLINE inlineResponse2008SummaryReturnedTransactionsL #-}

-- | 'inlineResponse2008SummaryTransactions' Lens
inlineResponse2008SummaryTransactionsL :: Lens_' InlineResponse2008Summary (Maybe Int)
inlineResponse2008SummaryTransactionsL f InlineResponse2008Summary {..} = (\inlineResponse2008SummaryTransactions -> InlineResponse2008Summary {inlineResponse2008SummaryTransactions, ..}) <$> f inlineResponse2008SummaryTransactions
{-# INLINE inlineResponse2008SummaryTransactionsL #-}

-- * InlineResponse201

-- | 'inlineResponse201Summary' Lens
inlineResponse201SummaryL :: Lens_' InlineResponse201 (Maybe InlineResponse201Summary)
inlineResponse201SummaryL f InlineResponse201 {..} = (\inlineResponse201Summary -> InlineResponse201 {inlineResponse201Summary, ..}) <$> f inlineResponse201Summary
{-# INLINE inlineResponse201SummaryL #-}

-- | 'inlineResponse201Transactions' Lens
inlineResponse201TransactionsL :: Lens_' InlineResponse201 (Maybe [TransactionPostOutput])
inlineResponse201TransactionsL f InlineResponse201 {..} = (\inlineResponse201Transactions -> InlineResponse201 {inlineResponse201Transactions, ..}) <$> f inlineResponse201Transactions
{-# INLINE inlineResponse201TransactionsL #-}

-- * InlineResponse201Summary

-- | 'inlineResponse201SummaryRequestId' Lens
inlineResponse201SummaryRequestIdL :: Lens_' InlineResponse201Summary (Maybe Text)
inlineResponse201SummaryRequestIdL f InlineResponse201Summary {..} = (\inlineResponse201SummaryRequestId -> InlineResponse201Summary {inlineResponse201SummaryRequestId, ..}) <$> f inlineResponse201SummaryRequestId
{-# INLINE inlineResponse201SummaryRequestIdL #-}

-- * InlineResponse202

-- | 'inlineResponse202Message' Lens
inlineResponse202MessageL :: Lens_' InlineResponse202 (Maybe Text)
inlineResponse202MessageL f InlineResponse202 {..} = (\inlineResponse202Message -> InlineResponse202 {inlineResponse202Message, ..}) <$> f inlineResponse202Message
{-# INLINE inlineResponse202MessageL #-}

-- * InlineResponse413

-- | 'inlineResponse413Code' Lens
inlineResponse413CodeL :: Lens_' InlineResponse413 (Maybe Int)
inlineResponse413CodeL f InlineResponse413 {..} = (\inlineResponse413Code -> InlineResponse413 {inlineResponse413Code, ..}) <$> f inlineResponse413Code
{-# INLINE inlineResponse413CodeL #-}

-- | 'inlineResponse413Description' Lens
inlineResponse413DescriptionL :: Lens_' InlineResponse413 (Maybe Text)
inlineResponse413DescriptionL f InlineResponse413 {..} = (\inlineResponse413Description -> InlineResponse413 {inlineResponse413Description, ..}) <$> f inlineResponse413Description
{-# INLINE inlineResponse413DescriptionL #-}

-- | 'inlineResponse413Name' Lens
inlineResponse413NameL :: Lens_' InlineResponse413 (Maybe Text)
inlineResponse413NameL f InlineResponse413 {..} = (\inlineResponse413Name -> InlineResponse413 {inlineResponse413Name, ..}) <$> f inlineResponse413Name
{-# INLINE inlineResponse413NameL #-}

-- * Merchant

-- | 'merchantCategories' Lens
merchantCategoriesL :: Lens_' Merchant (Maybe [MerchantCategory])
merchantCategoriesL f Merchant {..} = (\merchantCategories -> Merchant {merchantCategories, ..}) <$> f merchantCategories
{-# INLINE merchantCategoriesL #-}

-- | 'merchantHeronId' Lens
merchantHeronIdL :: Lens_' Merchant (Maybe Text)
merchantHeronIdL f Merchant {..} = (\merchantHeronId -> Merchant {merchantHeronId, ..}) <$> f merchantHeronId
{-# INLINE merchantHeronIdL #-}

-- | 'merchantIconUrl' Lens
merchantIconUrlL :: Lens_' Merchant (Maybe Text)
merchantIconUrlL f Merchant {..} = (\merchantIconUrl -> Merchant {merchantIconUrl, ..}) <$> f merchantIconUrl
{-# INLINE merchantIconUrlL #-}

-- | 'merchantLogoUrl' Lens
merchantLogoUrlL :: Lens_' Merchant (Maybe Text)
merchantLogoUrlL f Merchant {..} = (\merchantLogoUrl -> Merchant {merchantLogoUrl, ..}) <$> f merchantLogoUrl
{-# INLINE merchantLogoUrlL #-}

-- | 'merchantName' Lens
merchantNameL :: Lens_' Merchant (Text)
merchantNameL f Merchant {..} = (\merchantName -> Merchant {merchantName, ..}) <$> f merchantName
{-# INLINE merchantNameL #-}

-- | 'merchantUrl' Lens
merchantUrlL :: Lens_' Merchant (Text)
merchantUrlL f Merchant {..} = (\merchantUrl -> Merchant {merchantUrl, ..}) <$> f merchantUrl
{-# INLINE merchantUrlL #-}

-- * MerchantCategory

-- | 'merchantCategoryCode' Lens
merchantCategoryCodeL :: Lens_' MerchantCategory (Text)
merchantCategoryCodeL f MerchantCategory {..} = (\merchantCategoryCode -> MerchantCategory {merchantCategoryCode, ..}) <$> f merchantCategoryCode
{-# INLINE merchantCategoryCodeL #-}

-- | 'merchantCategoryDescription' Lens
merchantCategoryDescriptionL :: Lens_' MerchantCategory (Maybe Text)
merchantCategoryDescriptionL f MerchantCategory {..} = (\merchantCategoryDescription -> MerchantCategory {merchantCategoryDescription, ..}) <$> f merchantCategoryDescription
{-# INLINE merchantCategoryDescriptionL #-}

-- | 'merchantCategorySlug' Lens
merchantCategorySlugL :: Lens_' MerchantCategory (Maybe Text)
merchantCategorySlugL f MerchantCategory {..} = (\merchantCategorySlug -> MerchantCategory {merchantCategorySlug, ..}) <$> f merchantCategorySlug
{-# INLINE merchantCategorySlugL #-}

-- * MerchantExtract

-- | 'merchantExtractCategories' Lens
merchantExtractCategoriesL :: Lens_' MerchantExtract (Maybe [MerchantCategory])
merchantExtractCategoriesL f MerchantExtract {..} = (\merchantExtractCategories -> MerchantExtract {merchantExtractCategories, ..}) <$> f merchantExtractCategories
{-# INLINE merchantExtractCategoriesL #-}

-- | 'merchantExtractConfidence' Lens
merchantExtractConfidenceL :: Lens_' MerchantExtract (Maybe Double)
merchantExtractConfidenceL f MerchantExtract {..} = (\merchantExtractConfidence -> MerchantExtract {merchantExtractConfidence, ..}) <$> f merchantExtractConfidence
{-# INLINE merchantExtractConfidenceL #-}

-- | 'merchantExtractHeronId' Lens
merchantExtractHeronIdL :: Lens_' MerchantExtract (Maybe Text)
merchantExtractHeronIdL f MerchantExtract {..} = (\merchantExtractHeronId -> MerchantExtract {merchantExtractHeronId, ..}) <$> f merchantExtractHeronId
{-# INLINE merchantExtractHeronIdL #-}

-- | 'merchantExtractIconUrl' Lens
merchantExtractIconUrlL :: Lens_' MerchantExtract (Maybe Text)
merchantExtractIconUrlL f MerchantExtract {..} = (\merchantExtractIconUrl -> MerchantExtract {merchantExtractIconUrl, ..}) <$> f merchantExtractIconUrl
{-# INLINE merchantExtractIconUrlL #-}

-- | 'merchantExtractLogoUrl' Lens
merchantExtractLogoUrlL :: Lens_' MerchantExtract (Maybe Text)
merchantExtractLogoUrlL f MerchantExtract {..} = (\merchantExtractLogoUrl -> MerchantExtract {merchantExtractLogoUrl, ..}) <$> f merchantExtractLogoUrl
{-# INLINE merchantExtractLogoUrlL #-}

-- | 'merchantExtractName' Lens
merchantExtractNameL :: Lens_' MerchantExtract (Maybe Text)
merchantExtractNameL f MerchantExtract {..} = (\merchantExtractName -> MerchantExtract {merchantExtractName, ..}) <$> f merchantExtractName
{-# INLINE merchantExtractNameL #-}

-- | 'merchantExtractUrl' Lens
merchantExtractUrlL :: Lens_' MerchantExtract (Maybe Text)
merchantExtractUrlL f MerchantExtract {..} = (\merchantExtractUrl -> MerchantExtract {merchantExtractUrl, ..}) <$> f merchantExtractUrl
{-# INLINE merchantExtractUrlL #-}

-- * MerchantFeedback

-- | 'merchantFeedbackHeronId' Lens
merchantFeedbackHeronIdL :: Lens_' MerchantFeedback (Maybe Text)
merchantFeedbackHeronIdL f MerchantFeedback {..} = (\merchantFeedbackHeronId -> MerchantFeedback {merchantFeedbackHeronId, ..}) <$> f merchantFeedbackHeronId
{-# INLINE merchantFeedbackHeronIdL #-}

-- | 'merchantFeedbackIsCorrect' Lens
merchantFeedbackIsCorrectL :: Lens_' MerchantFeedback (Maybe Bool)
merchantFeedbackIsCorrectL f MerchantFeedback {..} = (\merchantFeedbackIsCorrect -> MerchantFeedback {merchantFeedbackIsCorrect, ..}) <$> f merchantFeedbackIsCorrect
{-# INLINE merchantFeedbackIsCorrectL #-}

-- | 'merchantFeedbackName' Lens
merchantFeedbackNameL :: Lens_' MerchantFeedback (Maybe Text)
merchantFeedbackNameL f MerchantFeedback {..} = (\merchantFeedbackName -> MerchantFeedback {merchantFeedbackName, ..}) <$> f merchantFeedbackName
{-# INLINE merchantFeedbackNameL #-}

-- * PaymentProcessor

-- | 'paymentProcessorHeronId' Lens
paymentProcessorHeronIdL :: Lens_' PaymentProcessor (Maybe Text)
paymentProcessorHeronIdL f PaymentProcessor {..} = (\paymentProcessorHeronId -> PaymentProcessor {paymentProcessorHeronId, ..}) <$> f paymentProcessorHeronId
{-# INLINE paymentProcessorHeronIdL #-}

-- | 'paymentProcessorName' Lens
paymentProcessorNameL :: Lens_' PaymentProcessor (Text)
paymentProcessorNameL f PaymentProcessor {..} = (\paymentProcessorName -> PaymentProcessor {paymentProcessorName, ..}) <$> f paymentProcessorName
{-# INLINE paymentProcessorNameL #-}

-- | 'paymentProcessorUrl' Lens
paymentProcessorUrlL :: Lens_' PaymentProcessor (Text)
paymentProcessorUrlL f PaymentProcessor {..} = (\paymentProcessorUrl -> PaymentProcessor {paymentProcessorUrl, ..}) <$> f paymentProcessorUrl
{-# INLINE paymentProcessorUrlL #-}

-- * TransactionAnnotation

-- | 'transactionAnnotationAnnotator' Lens
transactionAnnotationAnnotatorL :: Lens_' TransactionAnnotation (Maybe Text)
transactionAnnotationAnnotatorL f TransactionAnnotation {..} = (\transactionAnnotationAnnotator -> TransactionAnnotation {transactionAnnotationAnnotator, ..}) <$> f transactionAnnotationAnnotator
{-# INLINE transactionAnnotationAnnotatorL #-}

-- | 'transactionAnnotationConfidence' Lens
transactionAnnotationConfidenceL :: Lens_' TransactionAnnotation (Maybe Double)
transactionAnnotationConfidenceL f TransactionAnnotation {..} = (\transactionAnnotationConfidence -> TransactionAnnotation {transactionAnnotationConfidence, ..}) <$> f transactionAnnotationConfidence
{-# INLINE transactionAnnotationConfidenceL #-}

-- | 'transactionAnnotationHeronId' Lens
transactionAnnotationHeronIdL :: Lens_' TransactionAnnotation (Maybe Text)
transactionAnnotationHeronIdL f TransactionAnnotation {..} = (\transactionAnnotationHeronId -> TransactionAnnotation {transactionAnnotationHeronId, ..}) <$> f transactionAnnotationHeronId
{-# INLINE transactionAnnotationHeronIdL #-}

-- | 'transactionAnnotationLabel' Lens
transactionAnnotationLabelL :: Lens_' TransactionAnnotation (Maybe Text)
transactionAnnotationLabelL f TransactionAnnotation {..} = (\transactionAnnotationLabel -> TransactionAnnotation {transactionAnnotationLabel, ..}) <$> f transactionAnnotationLabel
{-# INLINE transactionAnnotationLabelL #-}

-- | 'transactionAnnotationModelVersion' Lens
transactionAnnotationModelVersionL :: Lens_' TransactionAnnotation (Maybe Text)
transactionAnnotationModelVersionL f TransactionAnnotation {..} = (\transactionAnnotationModelVersion -> TransactionAnnotation {transactionAnnotationModelVersion, ..}) <$> f transactionAnnotationModelVersion
{-# INLINE transactionAnnotationModelVersionL #-}

-- * TransactionFeedbackParams

-- | 'transactionFeedbackParamsTriggerWebhook' Lens
transactionFeedbackParamsTriggerWebhookL :: Lens_' TransactionFeedbackParams (Maybe Bool)
transactionFeedbackParamsTriggerWebhookL f TransactionFeedbackParams {..} = (\transactionFeedbackParamsTriggerWebhook -> TransactionFeedbackParams {transactionFeedbackParamsTriggerWebhook, ..}) <$> f transactionFeedbackParamsTriggerWebhook
{-# INLINE transactionFeedbackParamsTriggerWebhookL #-}

-- * TransactionFeedbackSchema

-- | 'transactionFeedbackSchemaCategory' Lens
transactionFeedbackSchemaCategoryL :: Lens_' TransactionFeedbackSchema (Maybe CategoryFeedback)
transactionFeedbackSchemaCategoryL f TransactionFeedbackSchema {..} = (\transactionFeedbackSchemaCategory -> TransactionFeedbackSchema {transactionFeedbackSchemaCategory, ..}) <$> f transactionFeedbackSchemaCategory
{-# INLINE transactionFeedbackSchemaCategoryL #-}

-- | 'transactionFeedbackSchemaMerchant' Lens
transactionFeedbackSchemaMerchantL :: Lens_' TransactionFeedbackSchema (Maybe MerchantFeedback)
transactionFeedbackSchemaMerchantL f TransactionFeedbackSchema {..} = (\transactionFeedbackSchemaMerchant -> TransactionFeedbackSchema {transactionFeedbackSchemaMerchant, ..}) <$> f transactionFeedbackSchemaMerchant
{-# INLINE transactionFeedbackSchemaMerchantL #-}

-- * TransactionGetOutput

-- | 'transactionGetOutputAccountId' Lens
transactionGetOutputAccountIdL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputAccountIdL f TransactionGetOutput {..} = (\transactionGetOutputAccountId -> TransactionGetOutput {transactionGetOutputAccountId, ..}) <$> f transactionGetOutputAccountId
{-# INLINE transactionGetOutputAccountIdL #-}

-- | 'transactionGetOutputAmount' Lens
transactionGetOutputAmountL :: Lens_' TransactionGetOutput (Double)
transactionGetOutputAmountL f TransactionGetOutput {..} = (\transactionGetOutputAmount -> TransactionGetOutput {transactionGetOutputAmount, ..}) <$> f transactionGetOutputAmount
{-# INLINE transactionGetOutputAmountL #-}

-- | 'transactionGetOutputBalance' Lens
transactionGetOutputBalanceL :: Lens_' TransactionGetOutput (Maybe Double)
transactionGetOutputBalanceL f TransactionGetOutput {..} = (\transactionGetOutputBalance -> TransactionGetOutput {transactionGetOutputBalance, ..}) <$> f transactionGetOutputBalance
{-# INLINE transactionGetOutputBalanceL #-}

-- | 'transactionGetOutputCategories' Lens
transactionGetOutputCategoriesL :: Lens_' TransactionGetOutput (Maybe [TransactionAnnotation])
transactionGetOutputCategoriesL f TransactionGetOutput {..} = (\transactionGetOutputCategories -> TransactionGetOutput {transactionGetOutputCategories, ..}) <$> f transactionGetOutputCategories
{-# INLINE transactionGetOutputCategoriesL #-}

-- | 'transactionGetOutputCreated' Lens
transactionGetOutputCreatedL :: Lens_' TransactionGetOutput (Maybe DateTime)
transactionGetOutputCreatedL f TransactionGetOutput {..} = (\transactionGetOutputCreated -> TransactionGetOutput {transactionGetOutputCreated, ..}) <$> f transactionGetOutputCreated
{-# INLINE transactionGetOutputCreatedL #-}

-- | 'transactionGetOutputCurrency' Lens
transactionGetOutputCurrencyL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputCurrencyL f TransactionGetOutput {..} = (\transactionGetOutputCurrency -> TransactionGetOutput {transactionGetOutputCurrency, ..}) <$> f transactionGetOutputCurrency
{-# INLINE transactionGetOutputCurrencyL #-}

-- | 'transactionGetOutputDescription' Lens
transactionGetOutputDescriptionL :: Lens_' TransactionGetOutput (Text)
transactionGetOutputDescriptionL f TransactionGetOutput {..} = (\transactionGetOutputDescription -> TransactionGetOutput {transactionGetOutputDescription, ..}) <$> f transactionGetOutputDescription
{-# INLINE transactionGetOutputDescriptionL #-}

-- | 'transactionGetOutputDescriptionClean' Lens
transactionGetOutputDescriptionCleanL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputDescriptionCleanL f TransactionGetOutput {..} = (\transactionGetOutputDescriptionClean -> TransactionGetOutput {transactionGetOutputDescriptionClean, ..}) <$> f transactionGetOutputDescriptionClean
{-# INLINE transactionGetOutputDescriptionCleanL #-}

-- | 'transactionGetOutputDuplicateOfId' Lens
transactionGetOutputDuplicateOfIdL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputDuplicateOfIdL f TransactionGetOutput {..} = (\transactionGetOutputDuplicateOfId -> TransactionGetOutput {transactionGetOutputDuplicateOfId, ..}) <$> f transactionGetOutputDuplicateOfId
{-# INLINE transactionGetOutputDuplicateOfIdL #-}

-- | 'transactionGetOutputEndUserId' Lens
transactionGetOutputEndUserIdL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputEndUserIdL f TransactionGetOutput {..} = (\transactionGetOutputEndUserId -> TransactionGetOutput {transactionGetOutputEndUserId, ..}) <$> f transactionGetOutputEndUserId
{-# INLINE transactionGetOutputEndUserIdL #-}

-- | 'transactionGetOutputHasMatchingTransaction' Lens
transactionGetOutputHasMatchingTransactionL :: Lens_' TransactionGetOutput (Maybe Bool)
transactionGetOutputHasMatchingTransactionL f TransactionGetOutput {..} = (\transactionGetOutputHasMatchingTransaction -> TransactionGetOutput {transactionGetOutputHasMatchingTransaction, ..}) <$> f transactionGetOutputHasMatchingTransaction
{-# INLINE transactionGetOutputHasMatchingTransactionL #-}

-- | 'transactionGetOutputHeronId' Lens
transactionGetOutputHeronIdL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputHeronIdL f TransactionGetOutput {..} = (\transactionGetOutputHeronId -> TransactionGetOutput {transactionGetOutputHeronId, ..}) <$> f transactionGetOutputHeronId
{-# INLINE transactionGetOutputHeronIdL #-}

-- | 'transactionGetOutputIsPotentialDuplicate' Lens
transactionGetOutputIsPotentialDuplicateL :: Lens_' TransactionGetOutput (Maybe Bool)
transactionGetOutputIsPotentialDuplicateL f TransactionGetOutput {..} = (\transactionGetOutputIsPotentialDuplicate -> TransactionGetOutput {transactionGetOutputIsPotentialDuplicate, ..}) <$> f transactionGetOutputIsPotentialDuplicate
{-# INLINE transactionGetOutputIsPotentialDuplicateL #-}

-- | 'transactionGetOutputIsRecurring' Lens
transactionGetOutputIsRecurringL :: Lens_' TransactionGetOutput (Maybe Bool)
transactionGetOutputIsRecurringL f TransactionGetOutput {..} = (\transactionGetOutputIsRecurring -> TransactionGetOutput {transactionGetOutputIsRecurring, ..}) <$> f transactionGetOutputIsRecurring
{-# INLINE transactionGetOutputIsRecurringL #-}

-- | 'transactionGetOutputLastUpdated' Lens
transactionGetOutputLastUpdatedL :: Lens_' TransactionGetOutput (Maybe DateTime)
transactionGetOutputLastUpdatedL f TransactionGetOutput {..} = (\transactionGetOutputLastUpdated -> TransactionGetOutput {transactionGetOutputLastUpdated, ..}) <$> f transactionGetOutputLastUpdated
{-# INLINE transactionGetOutputLastUpdatedL #-}

-- | 'transactionGetOutputMccCode' Lens
transactionGetOutputMccCodeL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputMccCodeL f TransactionGetOutput {..} = (\transactionGetOutputMccCode -> TransactionGetOutput {transactionGetOutputMccCode, ..}) <$> f transactionGetOutputMccCode
{-# INLINE transactionGetOutputMccCodeL #-}

-- | 'transactionGetOutputMerchant' Lens
transactionGetOutputMerchantL :: Lens_' TransactionGetOutput (Maybe Merchant)
transactionGetOutputMerchantL f TransactionGetOutput {..} = (\transactionGetOutputMerchant -> TransactionGetOutput {transactionGetOutputMerchant, ..}) <$> f transactionGetOutputMerchant
{-# INLINE transactionGetOutputMerchantL #-}

-- | 'transactionGetOutputPaymentProcessor' Lens
transactionGetOutputPaymentProcessorL :: Lens_' TransactionGetOutput (Maybe PaymentProcessor)
transactionGetOutputPaymentProcessorL f TransactionGetOutput {..} = (\transactionGetOutputPaymentProcessor -> TransactionGetOutput {transactionGetOutputPaymentProcessor, ..}) <$> f transactionGetOutputPaymentProcessor
{-# INLINE transactionGetOutputPaymentProcessorL #-}

-- | 'transactionGetOutputReferenceId' Lens
transactionGetOutputReferenceIdL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputReferenceIdL f TransactionGetOutput {..} = (\transactionGetOutputReferenceId -> TransactionGetOutput {transactionGetOutputReferenceId, ..}) <$> f transactionGetOutputReferenceId
{-# INLINE transactionGetOutputReferenceIdL #-}

-- | 'transactionGetOutputRequestId' Lens
transactionGetOutputRequestIdL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputRequestIdL f TransactionGetOutput {..} = (\transactionGetOutputRequestId -> TransactionGetOutput {transactionGetOutputRequestId, ..}) <$> f transactionGetOutputRequestId
{-# INLINE transactionGetOutputRequestIdL #-}

-- | 'transactionGetOutputTimestamp' Lens
transactionGetOutputTimestampL :: Lens_' TransactionGetOutput (Maybe DateTime)
transactionGetOutputTimestampL f TransactionGetOutput {..} = (\transactionGetOutputTimestamp -> TransactionGetOutput {transactionGetOutputTimestamp, ..}) <$> f transactionGetOutputTimestamp
{-# INLINE transactionGetOutputTimestampL #-}

-- | 'transactionGetOutputTransactionCode' Lens
transactionGetOutputTransactionCodeL :: Lens_' TransactionGetOutput (Maybe Text)
transactionGetOutputTransactionCodeL f TransactionGetOutput {..} = (\transactionGetOutputTransactionCode -> TransactionGetOutput {transactionGetOutputTransactionCode, ..}) <$> f transactionGetOutputTransactionCode
{-# INLINE transactionGetOutputTransactionCodeL #-}

-- * TransactionInput

-- | 'transactionInputAccountId' Lens
transactionInputAccountIdL :: Lens_' TransactionInput (Maybe Text)
transactionInputAccountIdL f TransactionInput {..} = (\transactionInputAccountId -> TransactionInput {transactionInputAccountId, ..}) <$> f transactionInputAccountId
{-# INLINE transactionInputAccountIdL #-}

-- | 'transactionInputAmount' Lens
transactionInputAmountL :: Lens_' TransactionInput (Double)
transactionInputAmountL f TransactionInput {..} = (\transactionInputAmount -> TransactionInput {transactionInputAmount, ..}) <$> f transactionInputAmount
{-# INLINE transactionInputAmountL #-}

-- | 'transactionInputBalance' Lens
transactionInputBalanceL :: Lens_' TransactionInput (Maybe Double)
transactionInputBalanceL f TransactionInput {..} = (\transactionInputBalance -> TransactionInput {transactionInputBalance, ..}) <$> f transactionInputBalance
{-# INLINE transactionInputBalanceL #-}

-- | 'transactionInputCategoriesDefault' Lens
transactionInputCategoriesDefaultL :: Lens_' TransactionInput (Maybe [Text])
transactionInputCategoriesDefaultL f TransactionInput {..} = (\transactionInputCategoriesDefault -> TransactionInput {transactionInputCategoriesDefault, ..}) <$> f transactionInputCategoriesDefault
{-# INLINE transactionInputCategoriesDefaultL #-}

-- | 'transactionInputCurrency' Lens
transactionInputCurrencyL :: Lens_' TransactionInput (Maybe Text)
transactionInputCurrencyL f TransactionInput {..} = (\transactionInputCurrency -> TransactionInput {transactionInputCurrency, ..}) <$> f transactionInputCurrency
{-# INLINE transactionInputCurrencyL #-}

-- | 'transactionInputDate' Lens
transactionInputDateL :: Lens_' TransactionInput (Maybe Date)
transactionInputDateL f TransactionInput {..} = (\transactionInputDate -> TransactionInput {transactionInputDate, ..}) <$> f transactionInputDate
{-# INLINE transactionInputDateL #-}

-- | 'transactionInputDescription' Lens
transactionInputDescriptionL :: Lens_' TransactionInput (Text)
transactionInputDescriptionL f TransactionInput {..} = (\transactionInputDescription -> TransactionInput {transactionInputDescription, ..}) <$> f transactionInputDescription
{-# INLINE transactionInputDescriptionL #-}

-- | 'transactionInputEndUserId' Lens
transactionInputEndUserIdL :: Lens_' TransactionInput (Maybe Text)
transactionInputEndUserIdL f TransactionInput {..} = (\transactionInputEndUserId -> TransactionInput {transactionInputEndUserId, ..}) <$> f transactionInputEndUserId
{-# INLINE transactionInputEndUserIdL #-}

-- | 'transactionInputMccCode' Lens
transactionInputMccCodeL :: Lens_' TransactionInput (Maybe Text)
transactionInputMccCodeL f TransactionInput {..} = (\transactionInputMccCode -> TransactionInput {transactionInputMccCode, ..}) <$> f transactionInputMccCode
{-# INLINE transactionInputMccCodeL #-}

-- | 'transactionInputMerchantName' Lens
transactionInputMerchantNameL :: Lens_' TransactionInput (Maybe Text)
transactionInputMerchantNameL f TransactionInput {..} = (\transactionInputMerchantName -> TransactionInput {transactionInputMerchantName, ..}) <$> f transactionInputMerchantName
{-# INLINE transactionInputMerchantNameL #-}

-- | 'transactionInputReferenceId' Lens
transactionInputReferenceIdL :: Lens_' TransactionInput (Maybe Text)
transactionInputReferenceIdL f TransactionInput {..} = (\transactionInputReferenceId -> TransactionInput {transactionInputReferenceId, ..}) <$> f transactionInputReferenceId
{-# INLINE transactionInputReferenceIdL #-}

-- | 'transactionInputTimestamp' Lens
transactionInputTimestampL :: Lens_' TransactionInput (Maybe DateTime)
transactionInputTimestampL f TransactionInput {..} = (\transactionInputTimestamp -> TransactionInput {transactionInputTimestamp, ..}) <$> f transactionInputTimestamp
{-# INLINE transactionInputTimestampL #-}

-- | 'transactionInputTransactionCode' Lens
transactionInputTransactionCodeL :: Lens_' TransactionInput (Maybe Text)
transactionInputTransactionCodeL f TransactionInput {..} = (\transactionInputTransactionCode -> TransactionInput {transactionInputTransactionCode, ..}) <$> f transactionInputTransactionCode
{-# INLINE transactionInputTransactionCodeL #-}

-- * TransactionPostOutput

-- | 'transactionPostOutputAccountId' Lens
transactionPostOutputAccountIdL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputAccountIdL f TransactionPostOutput {..} = (\transactionPostOutputAccountId -> TransactionPostOutput {transactionPostOutputAccountId, ..}) <$> f transactionPostOutputAccountId
{-# INLINE transactionPostOutputAccountIdL #-}

-- | 'transactionPostOutputAmount' Lens
transactionPostOutputAmountL :: Lens_' TransactionPostOutput (Double)
transactionPostOutputAmountL f TransactionPostOutput {..} = (\transactionPostOutputAmount -> TransactionPostOutput {transactionPostOutputAmount, ..}) <$> f transactionPostOutputAmount
{-# INLINE transactionPostOutputAmountL #-}

-- | 'transactionPostOutputBalance' Lens
transactionPostOutputBalanceL :: Lens_' TransactionPostOutput (Maybe Double)
transactionPostOutputBalanceL f TransactionPostOutput {..} = (\transactionPostOutputBalance -> TransactionPostOutput {transactionPostOutputBalance, ..}) <$> f transactionPostOutputBalance
{-# INLINE transactionPostOutputBalanceL #-}

-- | 'transactionPostOutputCategories' Lens
transactionPostOutputCategoriesL :: Lens_' TransactionPostOutput (Maybe [TransactionAnnotation])
transactionPostOutputCategoriesL f TransactionPostOutput {..} = (\transactionPostOutputCategories -> TransactionPostOutput {transactionPostOutputCategories, ..}) <$> f transactionPostOutputCategories
{-# INLINE transactionPostOutputCategoriesL #-}

-- | 'transactionPostOutputCurrency' Lens
transactionPostOutputCurrencyL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputCurrencyL f TransactionPostOutput {..} = (\transactionPostOutputCurrency -> TransactionPostOutput {transactionPostOutputCurrency, ..}) <$> f transactionPostOutputCurrency
{-# INLINE transactionPostOutputCurrencyL #-}

-- | 'transactionPostOutputDescription' Lens
transactionPostOutputDescriptionL :: Lens_' TransactionPostOutput (Text)
transactionPostOutputDescriptionL f TransactionPostOutput {..} = (\transactionPostOutputDescription -> TransactionPostOutput {transactionPostOutputDescription, ..}) <$> f transactionPostOutputDescription
{-# INLINE transactionPostOutputDescriptionL #-}

-- | 'transactionPostOutputDescriptionClean' Lens
transactionPostOutputDescriptionCleanL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputDescriptionCleanL f TransactionPostOutput {..} = (\transactionPostOutputDescriptionClean -> TransactionPostOutput {transactionPostOutputDescriptionClean, ..}) <$> f transactionPostOutputDescriptionClean
{-# INLINE transactionPostOutputDescriptionCleanL #-}

-- | 'transactionPostOutputDuplicateOfId' Lens
transactionPostOutputDuplicateOfIdL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputDuplicateOfIdL f TransactionPostOutput {..} = (\transactionPostOutputDuplicateOfId -> TransactionPostOutput {transactionPostOutputDuplicateOfId, ..}) <$> f transactionPostOutputDuplicateOfId
{-# INLINE transactionPostOutputDuplicateOfIdL #-}

-- | 'transactionPostOutputEndUserId' Lens
transactionPostOutputEndUserIdL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputEndUserIdL f TransactionPostOutput {..} = (\transactionPostOutputEndUserId -> TransactionPostOutput {transactionPostOutputEndUserId, ..}) <$> f transactionPostOutputEndUserId
{-# INLINE transactionPostOutputEndUserIdL #-}

-- | 'transactionPostOutputHasMatchingTransaction' Lens
transactionPostOutputHasMatchingTransactionL :: Lens_' TransactionPostOutput (Maybe Bool)
transactionPostOutputHasMatchingTransactionL f TransactionPostOutput {..} = (\transactionPostOutputHasMatchingTransaction -> TransactionPostOutput {transactionPostOutputHasMatchingTransaction, ..}) <$> f transactionPostOutputHasMatchingTransaction
{-# INLINE transactionPostOutputHasMatchingTransactionL #-}

-- | 'transactionPostOutputHeronId' Lens
transactionPostOutputHeronIdL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputHeronIdL f TransactionPostOutput {..} = (\transactionPostOutputHeronId -> TransactionPostOutput {transactionPostOutputHeronId, ..}) <$> f transactionPostOutputHeronId
{-# INLINE transactionPostOutputHeronIdL #-}

-- | 'transactionPostOutputIsPotentialDuplicate' Lens
transactionPostOutputIsPotentialDuplicateL :: Lens_' TransactionPostOutput (Maybe Bool)
transactionPostOutputIsPotentialDuplicateL f TransactionPostOutput {..} = (\transactionPostOutputIsPotentialDuplicate -> TransactionPostOutput {transactionPostOutputIsPotentialDuplicate, ..}) <$> f transactionPostOutputIsPotentialDuplicate
{-# INLINE transactionPostOutputIsPotentialDuplicateL #-}

-- | 'transactionPostOutputIsRecurring' Lens
transactionPostOutputIsRecurringL :: Lens_' TransactionPostOutput (Maybe Bool)
transactionPostOutputIsRecurringL f TransactionPostOutput {..} = (\transactionPostOutputIsRecurring -> TransactionPostOutput {transactionPostOutputIsRecurring, ..}) <$> f transactionPostOutputIsRecurring
{-# INLINE transactionPostOutputIsRecurringL #-}

-- | 'transactionPostOutputMccCode' Lens
transactionPostOutputMccCodeL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputMccCodeL f TransactionPostOutput {..} = (\transactionPostOutputMccCode -> TransactionPostOutput {transactionPostOutputMccCode, ..}) <$> f transactionPostOutputMccCode
{-# INLINE transactionPostOutputMccCodeL #-}

-- | 'transactionPostOutputMerchant' Lens
transactionPostOutputMerchantL :: Lens_' TransactionPostOutput (Maybe Merchant)
transactionPostOutputMerchantL f TransactionPostOutput {..} = (\transactionPostOutputMerchant -> TransactionPostOutput {transactionPostOutputMerchant, ..}) <$> f transactionPostOutputMerchant
{-# INLINE transactionPostOutputMerchantL #-}

-- | 'transactionPostOutputPaymentProcessor' Lens
transactionPostOutputPaymentProcessorL :: Lens_' TransactionPostOutput (Maybe PaymentProcessor)
transactionPostOutputPaymentProcessorL f TransactionPostOutput {..} = (\transactionPostOutputPaymentProcessor -> TransactionPostOutput {transactionPostOutputPaymentProcessor, ..}) <$> f transactionPostOutputPaymentProcessor
{-# INLINE transactionPostOutputPaymentProcessorL #-}

-- | 'transactionPostOutputReferenceId' Lens
transactionPostOutputReferenceIdL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputReferenceIdL f TransactionPostOutput {..} = (\transactionPostOutputReferenceId -> TransactionPostOutput {transactionPostOutputReferenceId, ..}) <$> f transactionPostOutputReferenceId
{-# INLINE transactionPostOutputReferenceIdL #-}

-- | 'transactionPostOutputRequestId' Lens
transactionPostOutputRequestIdL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputRequestIdL f TransactionPostOutput {..} = (\transactionPostOutputRequestId -> TransactionPostOutput {transactionPostOutputRequestId, ..}) <$> f transactionPostOutputRequestId
{-# INLINE transactionPostOutputRequestIdL #-}

-- | 'transactionPostOutputTimestamp' Lens
transactionPostOutputTimestampL :: Lens_' TransactionPostOutput (Maybe DateTime)
transactionPostOutputTimestampL f TransactionPostOutput {..} = (\transactionPostOutputTimestamp -> TransactionPostOutput {transactionPostOutputTimestamp, ..}) <$> f transactionPostOutputTimestamp
{-# INLINE transactionPostOutputTimestampL #-}

-- | 'transactionPostOutputTransactionCode' Lens
transactionPostOutputTransactionCodeL :: Lens_' TransactionPostOutput (Maybe Text)
transactionPostOutputTransactionCodeL f TransactionPostOutput {..} = (\transactionPostOutputTransactionCode -> TransactionPostOutput {transactionPostOutputTransactionCode, ..}) <$> f transactionPostOutputTransactionCode
{-# INLINE transactionPostOutputTransactionCodeL #-}
